name: Installer test

on:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    paths-ignore:
      - 'README.md'
      - '.editorconfig'
env:
  START_LOCAL_URL: "http://localhost:8080/start-local"

jobs:
  test:
    name: Test
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [macos-14]

    steps:
    - name: Install docker
      run: |
        brew install docker docker-compose colima
        colima delete
        colima start --arch aarch64
        sudo docker version

    - name: Checkout
      uses: actions/checkout@v4

    - name: Install bashunit
      run: |
        curl -s https://bashunit.typeddevs.com/install.sh | bash

    - name: Cache Docker images
      uses: ScribeMD/docker-cache@0.5.0
      with:
        key: docker-${{ runner.os }}-${{ hashFiles('start-local.sh') }}
        
    - name: Run the ARM64 tests
      run: |
        ./lib/bashunit tests/test_arm64.sh